# Inherits default site-unspecific frontend policy mutations (enabled per default)
inheritDefault: true
mutations:
  - mode: set
    directive: 'default-src'
    sources:
      - "'self'"

  - mode: extend
    directive: 'connect-src'
    sources:
      - "https://feedback.shopvote.de"
      - "https://www.sandbox.paypal.com"
      - "https://data.trapezblech-muenker.com"
      - "https://www.paypal.com"
      - "https://widgets.shopvote.de"
      - "https://www.google-analytics.com"
      - "https://trapezblech-muenker.com"
      - "https://www.googletagmanager.com"
      - "https://consent.cookiefirst.com"
      - "https://edge.cookiefirst.com"
      - "https://data.muenker.com"
      - "https://api.cookiefirst.com"

  - mode: extend
    directive: 'font-src'
    sources:
      - "data:"
      - "https://fonts.gstatic.com"
      - "https://trapezblech-muenker.com"
      - "https://use.typekit.net"

  - mode: extend
    directive: 'frame-src'
    sources:
      - "https://www.sandbox.paypal.com"
      - "https://www.paypal.com"
      - "https://www.youtube-nocookie.com"
      - "https://trapezblech-muenker.com"
      - "https://consent.cookiefirst.com"
      - "https://edge.cookiefirst.com"
      - "https://widgets.shopvote.de"
      - "https://www.google.com"
      - "https://snazzymaps.com"
      - "https://maps.googleapis.com"

  - mode: extend
    directive: 'img-src'
    sources:
      - "data:"
      - "blob:"
      - "https://www.trapezblech-muenker.com"
      - "https://www.paypalobjects.com"
      - "https://img.youtube.com"
      - "https://img.shopvote.de"
      - "https://i.ytimg.com"
      - "https://yt3.ggpht.com"
      - "https://data.trapezblech-muenker.com"
      - "https://trapezblech-muenker.com"
      - "https://widgets.shopvote.de"
      - "https://consent.cookiefirst.com"
      - "https://t.paypal.com"
      - "https://www.googletagmanager.com"
      - "https://googleads.g.doubleclick.net"
      - "https://data.muenker.com"
      - "https://www.google.com"
      - "https://www.google.de"

  - mode: set
    directive: 'media-src'
    sources:
      - "'self'"

  - mode: set
    directive: 'object-src'
    sources:
      - "'none'"

  - mode: extend
    directive: 'script-src'
    sources:
      -  "'self'"
      - "'nonce-{nonce}'"
      - "https://bat.bing.com"
      - "https://feedback.shopvote.de"
      - "https://www.paypal.com"
      - "https://www.gstatic.com"
      - "https://www.googletagmanager.com"
      - "https://trapezblech-muenker.com"
      - "https://www.google.com"
      - "https://widgets.shopvote.de"
      - "https://play.google.com"
      - "https://jnn-pa.googleapis.com"
      - "https://consent.cookiefirst.com"
      - "https://cdn.jsdelivr.net"

  - mode: extend
    directive: 'style-src'
    sources:
      - "'unsafe-inline'"
      - "'nonce-{nonce}'"
      - "https://muenker.ddev.site/typo3temp/"
      - "https://feedback.shopvote.de"
      - "https://fonts.googleapis.com"
      - "https://www.google.com"
      - "https://trapezblech-muenker.com"
      - "https://consent.cookiefirst.com"
      - "https://cdn.jsdelivr.net"
      - "https://use.typekit.net"
      - "https://p.typekit.net"

# Security Headers können nicht direkt in der CSP-Konfiguration gesetzt werden.
# Sie müssen separat in der Site-Konfiguration oder über den Server konfiguriert werden.