<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ri_glossar"
 *
 * Auto generated by Extension Builder 2014-05-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Riconet Glossar',
	'description' => 'Extends typo3 with a glossar',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'author_company' => '',
	'state' => 'stable',
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '9.5.0-11.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);