<?php
return [
    'BE' => [
        'debug' => false,
        'installToolPassword' => '$argon2i$v=19$m=65536,t=16,p=1$SElSa2dHQi9pUTlaUGZveQ$+XhvR90F5m0Jn+JWHAxYpvcx5Xb7CEIbWDTJM4iTKgY',
        'loginRateLimit' => 0,
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'driver' => 'mysqli',
            ],
        ],
    ],
    'EXTENSIONS' => [
        'backend' => [
            'backendFavicon' => '',
            'backendLogo' => '',
            'loginBackgroundImage' => '',
            'loginFootnote' => '',
            'loginHighlightColor' => '',
            'loginLogo' => '',
            'loginLogoAlt' => '',
        ],
        'extensionmanager' => [
            'automaticInstallation' => '1',
            'offlineMode' => '0',
        ],
        'ke_search' => [
            'additionalWordCharacters' => '',
            'allowEmptySearch' => '1',
            'enableExplicitAnd' => '0',
            'enablePartSearch' => '1',
            'finishNotification' => '0',
            'loglevel' => 'ERROR',
            'multiplyValueToTitle' => '1',
            'notificationRecipient' => '',
            'notificationSender' => 'no_reply@domain.com',
            'notificationSubject' => '[KE_SEARCH INDEXER NOTIFICATION]',
            'pathCatdoc' => '/usr/bin/',
            'pathPdfinfo' => '/usr/bin/',
            'pathPdftotext' => '/usr/bin/',
            'searchWordLength' => '4',
        ],
        'news' => [
            'advancedMediaPreview' => '1',
            'archiveDate' => 'date',
            'categoryBeGroupTceFormsRestriction' => '0',
            'categoryRestriction' => '',
            'contentElementPreview' => '1',
            'contentElementRelation' => '1',
            'dateTimeNotRequired' => '0',
            'hidePageTreeForAdministrationModule' => '0',
            'manualSorting' => '0',
            'mediaPreview' => 'false',
            'prependAtCopy' => '1',
            'resourceFolderImporter' => '/news_import',
            'rteForTeaser' => '0',
            'showAdministrationModule' => '1',
            'showImporter' => '0',
            'slugBehaviour' => 'unique',
            'storageUidImporter' => '1',
            'tagPid' => '1',
        ],
        'powermail' => [
            'disableBackendModule' => '0',
            'disableIpLog' => '1',
            'disableMarketingInformation' => '0',
            'disablePluginInformation' => '0',
            'disablePluginInformationMailPreview' => '0',
            'enableCaching' => '0',
            'l10n_mode_merge' => '0',
            'replaceIrreWithElementBrowser' => '0',
        ],
        'rx_shariff' => [
            'allowedDomains' => 'SERVER_NAME',
            'facebook_app_id' => '',
            'facebook_secret' => '',
            'services' => 'Facebook, LinkedIn, Reddit, StumbleUpon, Flattr, Pinterest, Xing, AddThis, Vk',
            'ttl' => '3600',
        ],
        'staticfilecache' => [
            'backendDisplayMode' => 'both',
            'boostMode' => '0',
            'cacheTagsEnable' => '0',
            'clearCacheForAllDomains' => '1',
            'debugHeaders' => '0',
            'disableInDevelopment' => '0',
            'enableGeneratorBrotli' => '0',
            'enableGeneratorGzip' => '1',
            'enableGeneratorManifest' => '0',
            'enableGeneratorPhp' => '0',
            'enableGeneratorPlain' => '0',
            'hashUriInCache' => '0',
            'htaccessTemplateName' => 'EXT:staticfilecache/Resources/Private/Templates/Htaccess.html',
            'inlineAssetsFileSize' => '50000',
            'inlineScriptMinify' => '0',
            'inlineServiceFavIcon' => '0',
            'inlineServiceScripts' => '0',
            'inlineServiceStyles' => '0',
            'inlineStyleAssets' => 'ico,png,woff2',
            'inlineStyleMinify' => '0',
            'largeIdentifierInCacheTable' => '0',
            'overrideCacheDirectory' => '',
            'phpTemplateName' => 'EXT:staticfilecache/Resources/Private/Templates/Php.html',
            'rawurldecodeCacheFileName' => '0',
            'renameTablesToOtherPrefix' => '0',
            'sendCacheControlHeaderRedirectAfterCacheTimeout' => '0',
            'sendHttp2PushEnable' => '0',
            'sendHttp2PushFileExtensions' => 'css,js',
            'sendHttp2PushFileLimit' => '10',
            'sendHttp2PushLimitToArea' => '',
            'useFallbackMiddleware' => '1',
            'useReverseUriLengthInPriority' => '1',
            'validFallbackHeaders' => 'Content-Type,Content-Language,Content-Security-Policy,Link,X-SFC-Tags',
            'validHtaccessHeaders' => 'Content-Type,Content-Language,Link,X-SFC-Tags',
        ],
        'vhs' => [
            'disableAssetHandling' => '0',
        ],
        'webp' => [
            'convert_all' => '1',
            'converter' => 'Plan2net\\Webp\\Converter\\MagickConverter',
            'exclude_directories' => '',
            'filter_pattern' => '/\\.(jpe?g|png|gif)\\.webp$/i',
            'hide_webp' => '1',
            'mime_types' => 'image/jpeg,image/png,image/gif',
            'parameters' => 'image/jpeg::-quality 85 -define webp:lossless=false|image/png::-quality 75 -define webp:lossless=true|image/gif::-quality 85 -define webp:lossless=true',
            'silent' => '0',
            'use_system_settings' => '1',
        ],
    ],
    'FE' => [
        'debug' => false,
        'disableNoCacheParameter' => true,
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
    ],
    'GFX' => [
        'gif_compress' => false,
        'imagefile_ext' => 'gif,jpg,jpeg,tif,tiff,bmp,pcx,tga,png,pdf,ai,svg,pdf',
        'processor' => 'GraphicsMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_allowUpscaling' => false,
        'processor_colorspace' => 'RGB',
        'processor_effects' => false,
        'processor_enabled' => true,
        'processor_path' => '/usr/local/bin/',
    ],
    'HTTP' => [
        'contentSecurityPolicy' => [
            'connect-src' => [
                '\'self\'',
                'https://feedback.shopvote.de',
                'https://www.sandbox.paypal.com',
                'https://data.trapezblech-muenker.com',
                'https://www.paypal.com',
                'https://widgets.shopvote.de',
                'https://www.google-analytics.com',
                'https://trapezblech-muenker.com',
                'https://www.googletagmanager.com',
                'https://consent.cookiefirst.com',
                'https://edge.cookiefirst.com',
                'https://data.muenker.com',
                'https://api.cookiefirst.com',
            ],
            'default-src' => [
                '\'self\'',
                '\'unsafe-inline\'',
            ],
            'font-src' => [
                '\'self\'',
                'https://fonts.gstatic.com',
                'https://trapezblech-muenker.com',
                'https://use.typekit.net',
            ],
            'frame-src' => [
                '\'self\'',
                'https://www.sandbox.paypal.com',
                'https://www.paypal.com',
                'https://www.youtube-nocookie.com',
                'https://trapezblech-muenker.com',
                'https://consent.cookiefirst.com',
                'https://edge.cookiefirst.com',
                'https://widgets.shopvote.de',
                'https://www.google.com',
                'https://snazzymaps.com',
                'https://maps.googleapis.com',
            ],
            'img-src' => [
                '\'self\'',
                'data:',
                'blob:',
                'https://www.trapezblech-muenker.com',
                'https://www.paypalobjects.com',
                'https://img.youtube.com',
                'https://img.shopvote.de',
                'https://i.ytimg.com',
                'https://yt3.ggpht.com',
                'https://data.trapezblech-muenker.com',
                'https://trapezblech-muenker.com',
                'https://widgets.shopvote.de',
                'https://consent.cookiefirst.com',
                'https://t.paypal.com',
                'https://www.googletagmanager.com',
                'https://googleads.g.doubleclick.net',
                'https://data.muenker.com',
                'https://www.google.com',
                'https://www.google.de',
            ],
            'media-src' => [
                '\'self\'',
            ],
            'object-src' => [
                '\'none\'',
            ],
            'script-src' => [
                '\'self\'',
                '\'unsafe-inline\'',
                'https://bat.bing.com',
                'https://feedback.shopvote.de',
                'https://www.paypal.com',
                'https://www.gstatic.com',
                'https://www.googletagmanager.com',
                'https://trapezblech-muenker.com',
                'https://www.google.com',
                'https://widgets.shopvote.de',
                'https://play.google.com',
                'https://jnn-pa.googleapis.com',
                'https://consent.cookiefirst.com',
                'https://cdn.jsdelivr.net',
            ],
            'style-src' => [
                '\'self\'',
                '\'unsafe-inline\'',
                'https://muenker.ddev.site/typo3temp/',
                'https://feedback.shopvote.de',
                'https://fonts.googleapis.com',
                'https://www.google.com',
                'https://trapezblech-muenker.com',
                'https://consent.cookiefirst.com',
                'https://cdn.jsdelivr.net',
                'https://use.typekit.net',
                'https://p.typekit.net',
            ],
        ],
        'securityHeaders' => [
            'Permissions-Policy' => 'geolocation=(), microphone=(), camera=()',
            'Referrer-Policy' => 'origin-when-cross-origin',
            'Strict-Transport-Security' => 'max-age=31536000; includeSubDomains; preload',
            'X-Content-Type-Options' => 'nosniff',
            'X-Frame-Options' => 'SAMEORIGIN',
        ],
    ],
    'LOG' => [
        'TYPO3' => [
            'CMS' => [
                'deprecations' => [
                    'writerConfiguration' => [
                        'notice' => [
                            'TYPO3\CMS\Core\Log\Writer\FileWriter' => [
                                'disabled' => true,
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    'MAIL' => [
        'transport' => 'sendmail',
        'transport_sendmail_command' => '/usr/local/bin/mailhog sendmail -t test@example.org --smtp-addr 127.0.0.1:1025',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
    'SYS' => [
        'caching' => [
            'cacheConfigurations' => [
                'hash' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                ],
                'imagesizes' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
                'pages' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
                'rootline' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
            ],
        ],
        'devIPmask' => '',
        'displayErrors' => 0,
        'encryptionKey' => '820f4f6cc3479334c1608f764369ecefd8fa7c9a75f30accd8b15c679c2cbfe7e35bc020b38dc1a6f17130f14a5fd81f',
        'exceptionalErrors' => 4096,
        'features' => [
            'security.frontend.enforceContentSecurityPolicy' => true,
            'security.frontend.reportContentSecurityPolicy' => false,
            'security.usePasswordPolicyForFrontendUsers' => true,
            'unifiedPageTranslationHandling' => true,
            'yamlImportsFollowDeclarationOrder' => true,
        ],
        'sitename' => 'Muenker',
        'systemMaintainers' => [
            1,
        ],
    ],
];
