<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rico_fluid_extend"
 *
 * Auto generated by Extension Builder 2016-01-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['fx_muenkercareer'] = array(
	'title' => 'Münker Career Layout',
	'description' => 'Templates and Layouts for muenker career',
	'category' => 'plugin',
	'author' => 'Felix Herrmann',
	'author_email' => 'info@failx.de',
	'state' => 'stable',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-11.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
